### ISSUE TITLE
[L4D2] Does not display the correct color after "2.2.0" version 

### ISSUE THREAD

**Issue by fbef0102** [Bara/Multi-Colors#16]
Game: Left 4 Dead 2
sm version: SourceMod Version: 1.11.0.6905

in .sp
```
	CPrintToChatAll("{red}RED, {olive}OLIVE, {green}GREEN, {lightgreen} LIGHTGREEN");
	CPrintToChatAll("{blue}BLUE, {default}DEFAULT");
```

in game
![image](https://user-images.githubusercontent.com/12229810/199160109-7bf465e8-5dd0-4e12-b65f-f292bf8e8872.png)

Edit:
For people who want to download "2.2.0" version, 
[Here](https://github.com/fbef0102/L4D1_2-Plugins/releases/tag/Multi-Colors)

**Comment by SefoNotasi** [comment]
Is there any progress on this problem?

I tried the latest version of Multi-Colors and the colors are still not displayed correctly in L4D2.

**Comment by Bara** [comment]
Not yet, I try to take a look this weekend or this week

**Comment by Bara** [comment]
> the colors are still not displayed correctly in L4D2.

Do you have a link for working colors version?

**Comment by fbef0102** [comment]
> 

Luckily, I have kept it before update
[multicolors.zip](https://github.com/Bara/Multi-Colors/files/11583317/multicolors.zip)
