### ISSUE TITLE
GetClientTeam: Client index 0 is invalid

### ISSUE THREAD

**Issue by dragokas** [Bara/Multi-Colors#4]
Hi,

> L 01/06/2020 - 23:56:07: [SM] Exception reported: Client index 0 is invalid
> L 01/06/2020 - 23:56:07: [SM] Blaming: simplewelcomemsg.smx
> L 01/06/2020 - 23:56:07: [SM] Call stack trace:
> L 01/06/2020 - 23:56:07: [SM]   [0] GetClientTeam
> L 01/06/2020 - 23:56:07: [SM]   [1] Line 407, d:\dev\SourceMod\addons\sourcemod\scripting\include\colors.inc::C_Format
> L 01/06/2020 - 23:56:07: [SM]   [2] Line 82, d:\dev\SourceMod\addons\sourcemod\scripting\include\colors.inc::C_PrintToChat
> L 01/06/2020 - 23:56:07: [SM]   [3] Line 142, H:\_To_games\Left4Dead_2\My_mods\Advertisements\SimpleWelcome\simplewelcomemsg.sp::ChatMessagesDisplay
> L 01/06/2020 - 23:56:07: [SM]   [4] Line 125, H:\_To_games\Left4Dead_2\My_mods\Advertisements\SimpleWelcome\simplewelcomemsg.sp::Timer_Welcome

colors.inc - Version: 2.0.0-MC (Author: exvel, Editor: Popoklopsi, Powerlord, Bara)
Game: L4d1.
src:
```
#include <colors>
Action ChatMessagesDisplay(int client)
{
	if (client && IsClientInGame(client))
	{
		if (g_iTankCount != 0)
			return Plugin_Continue;
		
		int iTotalLines = g_Cvar_LastLine.IntValue;
		g_iLineIdx[client]++;
		if ( g_iLineIdx[client] <= iTotalLines ) {
			static char msg[192];
			Format(msg, sizeof(msg), "WelcomeMsg%i", g_iLineIdx[client]);
			C_PrintToChat (client, "%t", msg, client);
			CPrintToConsoleEx(client, "%t", msg, client);
			return Plugin_Continue;
		}
		else {
			g_iLineIdx[client] = 0;
			CreateTimer (g_Cvar_PluginNextCycleTimer.FloatValue, Timer_BeginCycle, GetClientUserId(client), TIMER_FLAG_NO_MAPCHANGE);
			return Plugin_Stop;
		}
	}
	return Plugin_Stop;
}
```

Perhaps, I should use #include \<multicolors\> like in your example. I just noticed it.
However, I'm unsure it will resolve the issue (I not checked yet).
Leave decision about is it bug or no on you own.
Thanks.

**Comment by Bara** [comment]
Looks like an outdated/modified version. On line 82 is currently (master/322a81d) [Format](https://github.com/Bara/Multi-Colors/blob/master/addons/sourcemod/scripting/include/multicolors/colors.inc#L82) which shouldn't produce this error.

**Comment by dragokas** [comment]
Strange. Looks like modified version. Sorry for disturbing.

**Comment by Bara** [comment]
Feel free to open up it again, if you use the latest version and the issue still happens. ;)
