### ISSUE TITLE
CS:Source Colors issue.

### ISSUE THREAD

**Issue by 3GaNwO** [Bara/Multi-Colors#6]
I am using your morecolors.inc for a chat color producer and ran into a bunch of issues with the colors. It would appear that the list of 173 colors I only got about 40-50ish of them to work. I went through each color and a lot of them just appear as a green or yellow and not the actual color like a darkred or orange so on and so forth :/ would you like me to post the colors I did get working here for source? I figured I should let you know

**Comment by Bara** [comment]
https://github.com/Bara/Multi-Colors/blob/master/addons/sourcemod/scripting/include/multicolors/morecolors.inc#L817-L989
This should be the available colors.

**Comment by 3GaNwO** [comment]
Yes that is the list I put in my colors plugin and I tested each one in my Source server and a lot of them aren't functional. I will admit I did not log which "white" colors worked as I dont need like 10 shades of white but I know for sure orange didn't display as orange it was either a yellow or green. I went through all 173 of them and I think only about 40-50 work. Would you like me to list the colors I have tested to be working?

**Comment by Bara** [comment]
If it still happens, please provide a test case for reproducing your issue.

For now I close this issue.
