### ISSUE TITLE
[CSGO] Using two team colors in one message is not allowed

### ISSUE THREAD

**Issue by Nerus87** [Bara/Multi-Colors#8]
Hi, I have an error when using `darkred` color.

Translation:
```
"sm_qd_panel_defuse_nokit_incorrected_csgo"
	{
		"#format"		"{1:N},{2:s},{3:s},{4:s},{5:s}"
		"en"			"{blue}{1}{default} {darkred}detonated{default} the C4 with an incorrect {{2}}{3}{default} wire (7:8 odds).\nThe correct wire was {{4}}{5}{default}."
	}
```

Error:
```
L 02/02/2021 - 00:26:56: [SM] Exception reported: Using two team colors in one message is not allowed
L 02/02/2021 - 00:26:56: [SM] Blaming: quickdefuse.smx
L 02/02/2021 - 00:26:56: [SM] Call stack trace:
L 02/02/2021 - 00:26:56: [SM]   [0] ThrowError
L 02/02/2021 - 00:26:56: [SM]   [1] Line 410, D:\csgo-ffa\csgo\addons\sourcemod\scripting\include\multicolors/colors.inc::C_Format
L 02/02/2021 - 00:26:56: [SM]   [2] Line 85, D:\csgo-ffa\csgo\addons\sourcemod\scripting\include\multicolors/colors.inc::C_PrintToChat
L 02/02/2021 - 00:26:56: [SM]   [3] Line 104, D:\csgo-ffa\csgo\addons\sourcemod\scripting\include\multicolors.inc::CPrintToChatAll
L 02/02/2021 - 00:26:56: [SM]   [4] Line 229, .\quickdefuse.sp::PanelDefuseNoKit
```

Full code is on the [GitHub QuickDefuse](https://github.com/Nerus87/QuickDefuse)

**Comment by Bara** [comment]
Normally it comes from combining red/blue, darkred should be fine. When I look at your code, it is possible with a red/blue combination here: https://github.com/Nerus87/QuickDefuse/blob/master/addons/sourcemod/scripting/quickdefuse.sp#L25 and https://github.com/Nerus87/QuickDefuse/blob/master/addons/sourcemod/scripting/quickdefuse.sp#L229

**Comment by Bara** [comment]
And your "error" also exist in the [base version of color.inc](https://forums.alliedmods.net/showthread.php?t=96831), you can try to change playername color to `darkblue`. And by removing this check with 2 tema colors it could make some troubles in other games then csgo, so I'll keep it as it is.

**Comment by Nerus87** [comment]
Thanks, fixed, problem was on my plugin.

**Comment by Bara** [comment]
Thanks for your feedback!
